language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1

env:
  global:
    - CODECLIMATE_REPO_TOKEN=9c215b69f33357ece2af42829259ad13f704172c052587a22cefcee2450bcc71
  matrix:
    -
    - ACTIVE_RECORD_VERSION=3.2.0
    - ACTIVE_RECORD_VERSION=4.0.0
    - ACTIVE_RECORD_VERSION=4.1.0
    - ACTIVE_RECORD_VERSION=4.2.0.beta2

script: "bundle exec rake spec"

branches:
  only:
    - master
